### ISSUE TITLE
Collecte mail

### ISSUE THREAD

**Issue by apflieger** [apflieger/zigotoo#27]

**Comment by apflieger** [comment]
t'as du code la dessus ? Je pense qu'on en a plus besoin mais que ca peut devenir une page contact

**Comment by mbelkacemi** [comment]
Je voyais ça comme une inscription à newsletter, mais oui ça peut devenir
une page de contact
Le 11 févr. 2016 19:47, "Arnaud Pflieger" notifications@github.com a
écrit :

**Comment by apflieger** [comment]
Go push alors

**Comment by mbelkacemi** [comment]
Quelle est la différence entre "Créez votre site d'éleveur" , "Créez votre
page d'éleveur"?

**Comment by apflieger** [comment]
SEO
Faudrait trouver sur quel terme se placer pour avoir des chances d'être
référencé

2016-03-12 20:37 GMT+01:00 mbelkacemi notifications@github.com:
